### ISSUE TITLE
setActive is not working

### ISSUE THREAD

**Issue by csaq7151** [transferwise/sequence-layout#1]
Hi,
I need to set the steps dynamically to active or not depending on a status.
So I thought I set it programatically. But the setActive is not working.
However setTitle works fine. What is wrong with this code?
I dont want to use the Adapter if there is another way.

```
SequenceStep step_accepted;

step_accepted = rootView.findViewById(R.id.stepAccepted);
step_accepted.setActive(true);
```

xml
```
<com.transferwise.sequencelayout.SequenceLayout
                android:layout_marginTop="10dp"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <com.transferwise.sequencelayout.SequenceStep
                    android:id="@+id/stepAccepted"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:anchor="13:50"
                    app:title="@string/status_layout_order_accepted"
                    app:subtitle="@string/status_layout_order_accepted_subtitle"
                    app:subtitleTextAppearance="@style/TextAppearance.MaterialComponents.Subtitle1"
                    />
</com.transferwise.sequencelayout.SequenceLayout>
```

**Comment by saschoar** [comment]
Hey, could you try running `sequenceLayout.start()` after setting the active step programmatically? And, if you had another step set to active before, call `.setActive(false)` on that previous step?

**Comment by csaq7151** [comment]
@saschoar awesome thanks for the quick help. Calling `sequenceLayout.start()` worked!

**Comment by csaq7151** [comment]
@saschoar Do you know why sometimes it is working and sometimes not. I use it in a BottomSheet and when I open the sheet it displays everything fine. Then on the next app start without codechanges or anything else the active step is not set.

**Comment by csaq7151** [comment]
@saschoar it stopped working when I added my layout to a Bottomsheet. 
setActive is called and the Logs give me the correct values. However the sequencLayout.start() does nothing.
Any idea what could cause this issue?

**Comment by pratikbutani** [comment]
@saschoar so I have to call start() everytime when I active next step?

I have 25 steps, can you please tell me step to active it step by step.

**Comment by aRealBanana** [comment]
> Hi,
> I need to set the steps dynamically to active or not depending on a status.
> So I thought I set it programatically. But the setActive is not working.
> However setTitle works fine. What is wrong with this code?
> I dont want to use the Adapter if there is another way.
> 
> ```
> SequenceStep step_accepted;
> 
> step_accepted = rootView.findViewById(R.id.stepAccepted);
> step_accepted.setActive(true);
> ```
> 
> xml
> 
> ```
> <com.transferwise.sequencelayout.SequenceLayout
>                 android:layout_marginTop="10dp"
>                 android:layout_width="match_parent"
>                 android:layout_height="wrap_content">
> 
>                 <com.transferwise.sequencelayout.SequenceStep
>                     android:id="@+id/stepAccepted"
>                     android:layout_width="match_parent"
>                     android:layout_height="wrap_content"
>                     app:anchor="13:50"
>                     app:title="@string/status_layout_order_accepted"
>                     app:subtitle="@string/status_layout_order_accepted_subtitle"
>                     app:subtitleTextAppearance="@style/TextAppearance.MaterialComponents.Subtitle1"
>                     />
> </com.transferwise.sequencelayout.SequenceLayout>
> ```

could you please tell me how to user seqenceLayout.start()? 
i declared it as         SequenceLayout sequenceLayout = new SequenceLayout(MainActivity.this);
am new to android studio programming, did I miss something? should I add SequenceLayout class?
