### ISSUE TITLE
Starting from first point every time when I call start()

### ISSUE THREAD

**Issue by pratikbutani** [transferwise/sequence-layout#10]
I am working with 25 points that is used to show syncing process from server.

When one table got synced, I am activating second point.
Same as when second table got synced, I am activating third point. etc... etc..

I am doing following process while activating **any** point:

```
previousStep.setActive(false);
currentStep.setActive(true);
currentStep.setSubtitle("Getting data... Please wait...");
sequenceLayout.sequenceLayout.start();

```

With that code Its starting from first point every time even I reached last point.

Please help.

**Comment by saschoar** [comment]
Hey, you're right -- the current implementation is only meant to animate from the start to the current active step, not in between steps. If you'd like to add that functionality, checking out the animation logic in `SequenceLayout` would be a good start.

**Comment by pratikbutani** [comment]
Thank you for your reply. @saschoar I will try to go with that.. 

If you have any quick solution please do let me know as I have implemented your library in my current application and just this part is remaining.

**Comment by pratikbutani** [comment]
@saschoar  Can you please give me hint for this [code](https://github.com/transferwise/sequence-layout/blob/master/sequencelayout/src/main/java/com/transferwise/sequencelayout/SequenceLayout.kt#L182-L216)

I am not getting it actually so.

**Comment by pratikbutani** [comment]
Just commented [these two lines](https://github.com/transferwise/sequence-layout/blob/master/sequencelayout/src/main/java/com/transferwise/sequencelayout/SequenceLayout.kt#L177-L178)

```
progressBarForeground.pivotY = 0f
progressBarForeground.scaleY = 0f
```

That's happening just because its starting from zero every time.
