### ISSUE TITLE
 Failed to resolve: com.github.transferwise:sequence-layout:1.0.7

### ISSUE THREAD

**Issue by anjanaps** [transferwise/sequence-layout#12]
ERROR: Failed to resolve: com.github.transferwise:sequence-layout:1.0.7

**Comment by saschoar** [comment]
Hey, did you add the repo to your root build.gradle?

```
allprojects {
    repositories {
      maven { url "https://jitpack.io" }
    }
}
```

Also, try with the latest version which is 1.0.11
