### ISSUE TITLE
with many items, it doesn't scroll

### ISSUE THREAD

**Issue by hishambakr** [transferwise/sequence-layout#13]
Many thanks for the great widget. I face an issue when steps are a lot, it doesn't scroll and when I put it inside scroll view, the step height is weird and I have no direct way to control step height

**Comment by saschoar** [comment]
Hey, can you please share a simplified version of your layout XML? Have you checked / investigated scrolling it with the layout inspector?

The components for steps are normal views / view groups, so not too much magic there that would lead to issues in a scroll view.

**Comment by sadya** [comment]
use scrollview

**Comment by hishambakr** [comment]
I copied source code and played with layout until i fixed the issue. I will share code later as i am traveling now
