### ISSUE TITLE
can we manually decide that when a step will active

### ISSUE THREAD

**Issue by Mamta-Rana** [transferwise/sequence-layout#14]
I tried to set a step active by using setActive() method within a block other than onCreate. But this is not working.
I am unable to show the next step active manually.
Is there a way to set active a step manually?
What i want is Set a step active at run time on some action.
This is the code where i want to change the active step within click listener.
sequenceLayout.start() works only in OnCreate method
 step1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(Main2Activity.this, "clicked", Toast.LENGTH_SHORT).show();

                if (sequenceStep2.isActive()){
                    Toast.makeText(Main2Activity.this, "step 2 Active", Toast.LENGTH_SHORT).show();
                    sequenceStep2.setActive(false);
                    sequenceStep1.setActive(true);
                    sequenceLayout.start();
                }
                if (sequenceStep3.isActive()){
                    Toast.makeText(Main2Activity.this, "step 3 Active", Toast.LENGTH_SHORT).show();
                    sequenceStep3.setActive(false);
                    sequenceStep1.setActive(true);
                    sequenceLayout.start();
                }
                if (sequenceStep4.isActive()){
                    Toast.makeText(Main2Activity.this, "step 4 Active", Toast.LENGTH_SHORT).show();
                    sequenceStep4.setActive(false);
                    sequenceStep1.setActive(true);
                    sequenceLayout.start();
                }

                if (sequenceStep5.isActive()){
                    Toast.makeText(Main2Activity.this, "step 5 Active", Toast.LENGTH_SHORT).show();
                    sequenceStep5.setActive(false);
                    sequenceStep1.setActive(true);
                    sequenceLayout.start();
                }
            }
        });

**Comment by saschoar** [comment]
Hey, you're using `sequenceStep1.setActive(true)` and `sequenceLayout.start()` correctly actually. What  result do you see on screen when the click listener is triggered?

**Comment by Mamta-Rana** [comment]
I want to see the results like If I active step1 statically then i want that step2 will be active when click listener is triggered.

**Comment by saschoar** [comment]
> I want to see the results like If I active step1 statically then i want that step2 will be active when click listener is triggered.

Ok, so what does it do currently for you?

**Comment by Mamta-Rana** [comment]
it shows any step active statically but doesn't reply on dynamic cases.
Please provide me a solution by which i will be able to change the active
step.
