### ISSUE TITLE
setActive() seems to work when called in onCreate but not from Observable callback

### ISSUE THREAD

**Issue by yang-gu** [transferwise/sequence-layout#16]
When I call SequenceStep.setActive() from onCreate or any non-callback method it works fine, but I put it in an Observable's callback, setActive() never moves the sequence-layout even when logging statements indicate that the given part of the code was called. 

Sample: 

mutableData.observe(this, Observer { data ->
            if (data != null) {
                println("iscloudUp = " + isCloudUp)
                sequence.setActive(true)
            }
        })

**Comment by sbdevelopers** [comment]
I have same issue for SequenceStep.setActive() isn't working but I have solved that issue using adapter programmatically.
Try using Adapter and set data using a list in Java or Kotlin that will work.
I hope that will also work for you.

**Comment by saschoar** [comment]
Hey, this issue should be fixed in v1.1.1 (just released). No need to call `sequenceLayout.start()` anymore. The animation will automatically run if the active step or a step's size change.
