### ISSUE TITLE
vertical progress line now showing in Right to left layout(Arabic)

### ISSUE THREAD

**Issue by azarhaneef96** [transferwise/sequence-layout#17]
vertical progress line now showing in Right to left layout(Arabic)
![204223014_164630902312058_7317438634158394173_n](https://user-images.githubusercontent.com/36928244/122743671-3e7a5a80-d298-11eb-8ea2-1bb0515e79fa.png)
. please check this.

**Comment by anthonymonori** [comment]
Hi @azarhaneef96 could you please provide code sample or a reproduction project for us to investigate this better?
