### ISSUE TITLE
Library is not importing in new Android Studio Arctic Fox

### ISSUE THREAD

**Issue by nirajsonu** [transferwise/sequence-layout#35]
While importing the jitpack dependencies on gradle file it is not getting the classes of sequence layout.
Saying cannot resolve the sequence layout dependency

**Comment by saschoar** [comment]
Hey Neeraj, can you please share how you added the library, and which version you're using? Has it worked in a previous version, and have you tried a clean build? And if you're trying to build, what's the exact error message?

**Comment by nirajsonu** [comment]
Hi saschoar,
I have fixed the issue by adding jitpack url to setting.gradle insted to app-level gradle
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
      maven { url "https://jitpack.io" }
    }
}

and import module's build.gradle:
dependencies {
    implementation 'com.github.transferwise:sequence-layout:1.1.1'
}

and my issue is fixed I think this is for new version Android studio Arctic fox issue.
