### ISSUE TITLE
Is there a way to use the EditText for this?

### ISSUE THREAD

**Issue by meshileya** [transferwise/sequence-layout#5]
In the Sequence Step, is there a way i can manage EditText to collect input from users instead of having the app:title="First step"

**Comment by saschoar** [comment]
Hmm, you could modify the adapter so that you own views (instead of `SequenceStep`) are inflated and bind data to them.

**Comment by saschoar** [comment]
Closing this for now since -- let me know if you need more help to implement this, or create a PR.
